### ISSUE TITLE
Config marshal into json

### ISSUE THREAD

**Issue by FedorZaytsev** [lelvisl/logger#1]
Hi,

I think it will be great to replace mapping config struct into JSON. Usually, fields in JSON have naming with an underscore (_), but you have with space (example: https://github.com/lelvisl/logger/blob/master/logger.go#L14)

What to you think to replace `json:"network type"` into `json:"network_type"`

**Comment by lelvisl** [comment]
Yep, i’ll fix tag for json encoding
